"""Small, transport-only client for the Google Health API.

The Google Health API is the current Fitbit and Pixel device data surface.  A
caller supplies an access token that it obtained through its own OAuth flow;
this module deliberately has no database, user model, or FastAPI ownership.

Only the documented Health API v4 endpoints used by Runwise are exposed here.
In particular, this module does not accept arbitrary URLs or fall back to the
legacy Fitbit Web API.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date, datetime, timezone
import math
import re
import time
from typing import Any, Callable, Mapping
from urllib.parse import quote, urlencode
import xml.etree.ElementTree as ET

import httpx


GOOGLE_AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_HEALTH_BASE_URL = "https://health.googleapis.com/v4"

GOOGLEHEALTH_ACTIVITY_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly"
)
GOOGLEHEALTH_HEALTH_METRICS_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly"
)
GOOGLEHEALTH_LOCATION_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.location.readonly"
)

# Runwise needs all three read scopes for sessions, continuous heart-rate
# samples, and route export respectively.  They are kept as a tuple so the
# consent URL has a stable, testable order.
DEFAULT_GOOGLE_HEALTH_SCOPES = (
    GOOGLEHEALTH_ACTIVITY_SCOPE,
    GOOGLEHEALTH_HEALTH_METRICS_SCOPE,
    GOOGLEHEALTH_LOCATION_SCOPE,
)

_SUPPORTED_DATA_TYPES = frozenset(
    {
        "exercise",
        "heart-rate",
        "distance",
        "steps",
        "active-energy-burned",
        "active-zone-minutes",
    }
)
_DATA_TYPE_ALIASES = {
    "heart_rate": "heart-rate",
    "heart-rate": "heart-rate",
    "distance": "distance",
    "steps": "steps",
    "active_energy_burned": "active-energy-burned",
    "active-energy-burned": "active-energy-burned",
    "active_zone_minutes": "active-zone-minutes",
    "active-zone-minutes": "active-zone-minutes",
    "exercise": "exercise",
}


class GoogleHealthError(RuntimeError):
    """Base error raised by the OAuth or Google Health transport."""

    def __init__(
        self,
        message: str,
        *,
        status_code: int | None = None,
        details: Any = None,
        retry_after: float | None = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.details = details
        self.retry_after = retry_after


class GoogleHealthAuthError(GoogleHealthError):
    """The OAuth authorization-code or refresh-token request was rejected."""


class GoogleHealthRateLimitError(GoogleHealthError):
    """The API still returned 429 after the bounded retry budget."""


class GoogleHealthTimeoutError(GoogleHealthError):
    """The API did not respond within the configured timeout and retry budget."""


class GoogleHealthTransportError(GoogleHealthError):
    """A non-timeout network error prevented a request from completing."""


class GoogleHealthResponseError(GoogleHealthError):
    """The provider returned an invalid JSON or media response."""


def _required_text(value: str, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field_name} must be a non-empty string")
    return value.strip()


def build_authorization_url(
    client_id: str,
    redirect_uri: str,
    state: str,
    code_challenge: str,
) -> str:
    """Build the Google OAuth 2.0 authorization URL used by Runwise.

    ``code_challenge`` is a PKCE S256 challenge generated by the route owner.
    The matching verifier is accepted by :func:`exchange_code`.  ``state`` is
    always carried through so the route owner can validate CSRF protection.
    """

    params = {
        "client_id": _required_text(client_id, "client_id"),
        "redirect_uri": _required_text(redirect_uri, "redirect_uri"),
        "response_type": "code",
        "scope": " ".join(DEFAULT_GOOGLE_HEALTH_SCOPES),
        "access_type": "offline",
        "prompt": "consent",
        "state": _required_text(state, "state"),
        "code_challenge": _required_text(code_challenge, "code_challenge"),
        "code_challenge_method": "S256",
    }
    return f"{GOOGLE_AUTHORIZATION_ENDPOINT}?{urlencode(params)}"


def _token_post(
    data: Mapping[str, str],
    *,
    http_client: httpx.Client | None,
    timeout: float,
) -> dict[str, Any]:
    client = http_client or httpx.Client(timeout=timeout)
    try:
        try:
            response = client.post(
                GOOGLE_TOKEN_ENDPOINT,
                data=dict(data),
                headers={"Accept": "application/json"},
                timeout=timeout,
            )
        except httpx.TimeoutException as exc:
            raise GoogleHealthTimeoutError(
                "Google OAuth token request timed out"
            ) from exc
        except httpx.TransportError as exc:
            raise GoogleHealthTransportError(
                "Google OAuth token request failed"
            ) from exc

        try:
            payload = response.json()
        except ValueError as exc:
            payload = response.text[:2000]
            raise GoogleHealthResponseError(
                "Google OAuth returned a non-JSON response",
                status_code=response.status_code,
                details=payload,
            ) from exc
        if response.status_code < 200 or response.status_code >= 300:
            message = "Google OAuth token request was rejected"
            if isinstance(payload, Mapping):
                message = str(payload.get("error_description") or payload.get("error") or message)
            raise GoogleHealthAuthError(
                message,
                status_code=response.status_code,
                details=payload,
            )
        if not isinstance(payload, dict):
            raise GoogleHealthResponseError(
                "Google OAuth response must be a JSON object",
                status_code=response.status_code,
                details=payload,
            )
        return payload
    finally:
        if http_client is None:
            client.close()


def exchange_code(
    code: str,
    client_id: str,
    redirect_uri: str,
    client_secret: str | None = None,
    code_verifier: str | None = None,
    *,
    http_client: httpx.Client | None = None,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """Exchange an authorization code for Google OAuth tokens.

    The route owner should persist the returned ``refresh_token`` securely.
    ``client_secret`` is optional to support public PKCE clients; confidential
    clients should supply it.  The positional order is ``code, client_id,
    redirect_uri, client_secret, code_verifier`` and all arguments can also be
    supplied by keyword.
    """

    body: dict[str, str] = {
        "code": _required_text(code, "code"),
        "client_id": _required_text(client_id, "client_id"),
        "redirect_uri": _required_text(redirect_uri, "redirect_uri"),
        "grant_type": "authorization_code",
    }
    if client_secret is not None:
        body["client_secret"] = _required_text(client_secret, "client_secret")
    if code_verifier is not None:
        body["code_verifier"] = _required_text(code_verifier, "code_verifier")
    return _token_post(body, http_client=http_client, timeout=timeout)


def refresh_token(
    token: str,
    client_id: str,
    client_secret: str | None = None,
    *,
    http_client: httpx.Client | None = None,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """Refresh a Google OAuth access token using an offline refresh token."""

    body: dict[str, str] = {
        "refresh_token": _required_text(token, "refresh_token"),
        "client_id": _required_text(client_id, "client_id"),
        "grant_type": "refresh_token",
    }
    if client_secret is not None:
        body["client_secret"] = _required_text(client_secret, "client_secret")
    return _token_post(body, http_client=http_client, timeout=timeout)


def _canonical_data_type(data_type: str) -> str:
    if not isinstance(data_type, str):
        raise ValueError("data_type must be a string")
    canonical = _DATA_TYPE_ALIASES.get(data_type.strip().lower(), data_type.strip().lower())
    if canonical not in _SUPPORTED_DATA_TYPES:
        allowed = ", ".join(sorted(_SUPPORTED_DATA_TYPES))
        raise ValueError(f"unsupported Google Health data_type {data_type!r}; use one of: {allowed}")
    return canonical


def _parse_duration(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        number = float(value)
        return number if math.isfinite(number) and number >= 0 else None
    if isinstance(value, str):
        match = re.fullmatch(r"\s*([0-9]+(?:\.[0-9]+)?)s\s*", value)
        if match:
            return float(match.group(1))
    return None


def _parse_numeric(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _parse_timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip()
    if raw.endswith("Z"):
        raw = f"{raw[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _duration_between(start: Any, end: Any) -> float | None:
    first = _parse_timestamp(start)
    last = _parse_timestamp(end)
    if first is None or last is None:
        return None
    seconds = (last - first).total_seconds()
    return seconds if math.isfinite(seconds) and seconds >= 0 else None


def _format_filter_time(value: date | datetime | str, *, civil: bool) -> str:
    if isinstance(value, datetime):
        current = value
        if civil:
            if current.tzinfo is not None:
                current = current.astimezone().replace(tzinfo=None)
            return current.isoformat(timespec="seconds")
        if current.tzinfo is None:
            current = current.replace(tzinfo=timezone.utc)
        current = current.astimezone(timezone.utc)
        return current.isoformat(timespec="seconds").replace("+00:00", "Z")
    if isinstance(value, date):
        return value.isoformat() if civil else value.isoformat() + "T00:00:00Z"
    current = value.strip()
    if not current or '"' in current:
        raise ValueError("time filter values must be non-empty and cannot contain quotes")
    if not civil and re.fullmatch(r"\d{4}-\d{2}-\d{2}", current):
        return date.fromisoformat(current).isoformat() + "T00:00:00Z"
    return current


def _build_filter(
    data_type: str,
    start_time: date | datetime | str | None,
    end_time: date | datetime | str | None,
) -> str | None:
    if start_time is None and end_time is None:
        return None
    if data_type == "exercise":
        field = "exercise.interval.civil_start_time"
        civil = True
    elif data_type == "heart-rate":
        field = "heart_rate.sample_time.physical_time"
        civil = False
    else:
        snake_name = data_type.replace("-", "_")
        field = f"{snake_name}.interval.start_time"
        civil = False
    terms: list[str] = []
    if start_time is not None:
        terms.append(f'{field} >= "{_format_filter_time(start_time, civil=civil)}"')
    if end_time is not None:
        terms.append(f'{field} < "{_format_filter_time(end_time, civil=civil)}"')
    return " AND ".join(terms)


def _parse_retry_after(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        delay = float(value)
    except (TypeError, ValueError):
        return None
    return delay if math.isfinite(delay) and delay >= 0 else None


def _error_details(response: httpx.Response) -> Any:
    try:
        return response.json()
    except ValueError:
        return response.text[:2000]


def _resource_id(exercise_id: str) -> str:
    """Validate an exercise ID or its documented resource name."""

    raw = _required_text(exercise_id, "exercise_id")
    resource = re.fullmatch(r"users/[A-Za-z0-9_-]+/dataTypes/exercise/dataPoints/([A-Za-z0-9_-]{1,200})", raw)
    if resource:
        raw = resource.group(1)
    if "/" in raw or ":" in raw or not re.fullmatch(r"[A-Za-z0-9_-]{1,200}", raw):
        raise ValueError("exercise_id must be an ID or an exercise resource name")
    return raw


def _last_resource_component(name: Any) -> str | None:
    if not isinstance(name, str) or not name:
        return None
    return name.rstrip("/").split("/")[-1] or None


def _normalize_split(split: Mapping[str, Any]) -> dict[str, Any]:
    interval = split
    metrics = split.get("metricsSummary")
    metrics = metrics if isinstance(metrics, Mapping) else {}
    distance_mm = _parse_numeric(metrics.get("distanceMillimeters"))
    start_time = split.get("startTime")
    end_time = split.get("endTime")
    return {
        "start_time": start_time,
        "end_time": end_time,
        "active_duration_seconds": _parse_duration(split.get("activeDuration")),
        "elapsed_seconds": _duration_between(start_time, end_time),
        "distance_m": distance_mm / 1000.0 if distance_mm is not None else None,
        "split_type": split.get("splitType"),
        "raw": deepcopy(dict(split)),
    }


def _normalize_session(point: Mapping[str, Any]) -> dict[str, Any]:
    exercise = point.get("exercise")
    exercise = exercise if isinstance(exercise, Mapping) else {}
    interval = exercise.get("interval")
    interval = interval if isinstance(interval, Mapping) else {}
    metrics = exercise.get("metricsSummary")
    metrics = metrics if isinstance(metrics, Mapping) else {}
    metadata = exercise.get("exerciseMetadata")
    metadata = metadata if isinstance(metadata, Mapping) else {}
    name = point.get("name")
    start_time = interval.get("startTime")
    end_time = interval.get("endTime")
    distance_mm = _parse_numeric(metrics.get("distanceMillimeters"))
    distance_m = distance_mm / 1000.0 if distance_mm is not None else None
    active_duration = _parse_duration(exercise.get("activeDuration"))
    elapsed = _duration_between(start_time, end_time)
    average_hr = _parse_numeric(metrics.get("averageHeartRateBeatsPerMinute"))
    if average_hr is not None and average_hr.is_integer():
        average_hr = int(average_hr)
    default_name = exercise.get("displayName") or exercise.get("exerciseType") or "Exercise"
    splits = exercise.get("splitSummaries")
    if not isinstance(splits, list):
        splits = exercise.get("splits")
    normalized_splits = [
        _normalize_split(split)
        for split in (splits if isinstance(splits, list) else [])
        if isinstance(split, Mapping)
    ]
    events = exercise.get("exerciseEvents")
    normalized_events = [deepcopy(dict(event)) for event in events if isinstance(event, Mapping)] if isinstance(events, list) else []
    raw = deepcopy(dict(point))
    return {
        "provider": "google_health",
        "data_type": "exercise",
        "id": name,
        "source_id": name,
        "provider_id": _last_resource_component(name),
        "resource_name": name,
        "title": default_name,
        "display_name": exercise.get("displayName"),
        "activity_type": exercise.get("exerciseType"),
        "started_at": start_time,
        "ended_at": end_time,
        "elapsed_seconds": elapsed,
        "duration_seconds": elapsed,
        "active_duration_seconds": active_duration,
        "distance_m": distance_m,
        "distance_km": distance_m / 1000.0 if distance_m is not None else None,
        "average_hr_bpm": average_hr,
        "avg_hr": average_hr,
        "average_speed_mps": (
            _parse_numeric(metrics.get("averageSpeedMillimetersPerSecond")) / 1000.0
            if _parse_numeric(metrics.get("averageSpeedMillimetersPerSecond")) is not None
            else None
        ),
        "average_pace_seconds_per_meter": _parse_numeric(metrics.get("averagePaceSecondsPerMeter")),
        "has_gps": metadata.get("hasGps"),
        "exercise_events": normalized_events,
        "splits": normalized_splits,
        "raw": raw,
    }


def _normalize_sample(data_type: str, point: Mapping[str, Any]) -> dict[str, Any]:
    raw = deepcopy(dict(point))
    payload = point.get(data_type.replace("-", ""))
    if data_type == "heart-rate":
        payload = point.get("heartRate")
        payload = payload if isinstance(payload, Mapping) else {}
        sample_time = payload.get("sampleTime")
        sample_time = sample_time if isinstance(sample_time, Mapping) else {}
        bpm = _parse_numeric(payload.get("beatsPerMinute"))
        if bpm is not None and bpm.is_integer():
            bpm = int(bpm)
        return {
            "provider": "google_health",
            "data_type": data_type,
            "id": point.get("name"),
            "timestamp": sample_time.get("physicalTime"),
            "sample_time": sample_time.get("physicalTime"),
            "heart_rate_bpm": bpm,
            "bpm": bpm,
            "metadata": deepcopy(payload.get("metadata")) if isinstance(payload.get("metadata"), Mapping) else {},
            "raw": raw,
        }
    if data_type in {"distance", "steps", "active-energy-burned", "active-zone-minutes"}:
        field_name = {
            "distance": "distance",
            "steps": "steps",
            "active-energy-burned": "activeEnergyBurned",
            "active-zone-minutes": "activeZoneMinutes",
        }[data_type]
        payload = point.get(field_name)
        payload = payload if isinstance(payload, Mapping) else {}
        interval = payload.get("interval")
        interval = interval if isinstance(interval, Mapping) else {}
        raw_value = payload.get("millimeters") if data_type == "distance" else payload.get("count")
        if data_type == "active-energy-burned":
            raw_value = payload.get("calories") or payload.get("caloriesKcal")
        if data_type == "active-zone-minutes":
            raw_value = payload.get("activeZoneMinutes")
        numeric_value = _parse_numeric(raw_value)
        if data_type == "distance" and numeric_value is not None:
            numeric_value = numeric_value / 1000.0
        return {
            "provider": "google_health",
            "data_type": data_type,
            "id": point.get("name"),
            "start_time": interval.get("startTime"),
            "end_time": interval.get("endTime"),
            "timestamp": interval.get("startTime"),
            "elapsed_seconds": _duration_between(interval.get("startTime"), interval.get("endTime")),
            "value": numeric_value,
            "distance_m": numeric_value if data_type == "distance" else None,
            "raw": raw,
        }
    return {
        "provider": "google_health",
        "data_type": data_type,
        "id": point.get("name"),
        "raw": raw,
    }


def _parse_tcx_points(raw_tcx: bytes) -> list[dict[str, Any]]:
    try:
        root = ET.fromstring(raw_tcx)
    except (ET.ParseError, TypeError) as exc:
        raise GoogleHealthResponseError("Google Health returned invalid TCX XML") from exc

    points: list[dict[str, Any]] = []
    for element in root.iter():
        if element.tag.rsplit("}", 1)[-1] != "Trackpoint":
            continue
        values: dict[str, Any] = {}
        for child in element.iter():
            key = child.tag.rsplit("}", 1)[-1]
            if child is element or child.text is None:
                continue
            text = child.text.strip()
            if key in {"LatitudeDegrees", "LongitudeDegrees", "AltitudeMeters", "DistanceMeters"}:
                try:
                    values[key] = float(text)
                except ValueError:
                    values[key] = None
            elif key == "Time":
                values[key] = text
        lat = values.get("LatitudeDegrees")
        lon = values.get("LongitudeDegrees")
        points.append(
            {
                "timestamp": values.get("Time"),
                "lat": lat,
                "lon": lon,
                "altitude_m": values.get("AltitudeMeters"),
                "distance_m": values.get("DistanceMeters"),
                "raw": deepcopy(values),
            }
        )
    return points


class GoogleHealthClient:
    """Synchronous Google Health API v4 client with bounded retries.

    ``http_client`` is injectable for tests (for example an ``httpx.Client``
    using ``MockTransport``).  In production the client owns a normal
    ``httpx.Client`` and can be closed directly or through a context manager.
    ``max_retries`` counts retries after the initial request.
    """

    def __init__(
        self,
        access_token: str,
        *,
        http_client: httpx.Client | None = None,
        timeout: float = 15.0,
        max_retries: int = 2,
        backoff_base: float = 0.25,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        self.access_token = _required_text(access_token, "access_token")
        if timeout <= 0 or not math.isfinite(timeout):
            raise ValueError("timeout must be a finite positive number")
        if max_retries < 0:
            raise ValueError("max_retries cannot be negative")
        if backoff_base < 0 or not math.isfinite(backoff_base):
            raise ValueError("backoff_base must be finite and non-negative")
        self.timeout = float(timeout)
        self.max_retries = int(max_retries)
        self.backoff_base = float(backoff_base)
        self._sleep = sleep
        self._http_client = http_client or httpx.Client(timeout=self.timeout)
        self._owns_http_client = http_client is None

    def close(self) -> None:
        if self._owns_http_client:
            self._http_client.close()
            self._owns_http_client = False

    def __enter__(self) -> "GoogleHealthClient":
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        self.close()

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Mapping[str, Any] | None = None,
        binary: bool = False,
    ) -> httpx.Response:
        if not path.startswith("/users/me/"):
            raise ValueError("Google Health paths must use the fixed users/me API surface")
        url = f"{GOOGLE_HEALTH_BASE_URL}{path}"
        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Accept": "application/octet-stream" if binary else "application/json",
        }
        last_timeout: httpx.TimeoutException | None = None
        for attempt in range(self.max_retries + 1):
            try:
                response = self._http_client.request(
                    method,
                    url,
                    params=dict(params or {}),
                    headers=headers,
                    timeout=self.timeout,
                )
            except httpx.TimeoutException as exc:
                last_timeout = exc
                if attempt < self.max_retries:
                    self._sleep(min(5.0, self.backoff_base * (2**attempt)))
                    continue
                raise GoogleHealthTimeoutError(
                    "Google Health API request timed out"
                ) from exc
            except httpx.TransportError as exc:
                raise GoogleHealthTransportError(
                    "Google Health API request failed"
                ) from exc

            if response.status_code not in {429, 500, 502, 503, 504}:
                break
            if attempt >= self.max_retries:
                break
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            delay = retry_after if retry_after is not None else self.backoff_base * (2**attempt)
            self._sleep(min(5.0, max(0.0, delay)))

        if response.status_code == 429:
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            raise GoogleHealthRateLimitError(
                "Google Health API rate limit exceeded",
                status_code=429,
                details=_error_details(response),
                retry_after=retry_after,
            )
        if response.status_code < 200 or response.status_code >= 300:
            raise GoogleHealthError(
                f"Google Health API returned HTTP {response.status_code}",
                status_code=response.status_code,
                details=_error_details(response),
                retry_after=_parse_retry_after(response.headers.get("Retry-After")),
            )
        return response

    def _request_json(
        self,
        path: str,
        *,
        params: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        response = self._request("GET", path, params=params)
        try:
            payload = response.json()
        except ValueError as exc:
            raise GoogleHealthResponseError(
                "Google Health API returned a non-JSON response",
                status_code=response.status_code,
                details=response.text[:2000],
            ) from exc
        if not isinstance(payload, dict):
            raise GoogleHealthResponseError(
                "Google Health API list response must be a JSON object",
                status_code=response.status_code,
                details=payload,
            )
        return payload

    def list_data_points(
        self,
        data_type: str,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = None,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch one documented ``dataPoints.list`` page.

        Google orders list results by interval/sample start time descending.
        ``next_page_token`` in the returned dict must be supplied to the next
        call to continue historical retrieval.
        """

        canonical = _canonical_data_type(data_type)
        params: dict[str, Any] = {}
        if page_size is not None:
            if isinstance(page_size, bool) or not isinstance(page_size, int) or page_size <= 0:
                raise ValueError("page_size must be a positive integer")
            max_page_size = 25 if canonical == "exercise" else 10_000
            params["pageSize"] = min(page_size, max_page_size)
        if page_token is not None:
            params["pageToken"] = _required_text(page_token, "page_token")
        generated_filter = _build_filter(canonical, start_time, end_time)
        if filter_expression is not None:
            if not isinstance(filter_expression, str) or not filter_expression.strip():
                raise ValueError("filter_expression must be a non-empty string")
            params["filter"] = filter_expression.strip()
        elif generated_filter is not None:
            params["filter"] = generated_filter
        payload = self._request_json(
            f"/users/me/dataTypes/{canonical}/dataPoints",
            params=params,
        )
        points = payload.get("dataPoints")
        if points is None:
            points = []
        if not isinstance(points, list):
            raise GoogleHealthResponseError(
                "Google Health API response dataPoints must be an array",
                details=payload,
            )
        token = payload.get("nextPageToken")
        if token is not None and not isinstance(token, str):
            raise GoogleHealthResponseError(
                "Google Health API nextPageToken must be a string",
                details=payload,
            )
        return {
            "data_type": canonical,
            "data_points": [deepcopy(point) for point in points if isinstance(point, Mapping)],
            "next_page_token": token or None,
            "raw": deepcopy(payload),
        }

    def fetch_activity_sessions(
        self,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = 25,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch and normalize one ``exercise`` session page."""

        page = self.list_data_points(
            "exercise",
            start_time,
            end_time,
            page_token=page_token,
            page_size=page_size,
            filter_expression=filter_expression,
        )
        sessions = [_normalize_session(point) for point in page["data_points"]]
        return {
            "data_type": "exercise",
            "sessions": sessions,
            "data": sessions,
            "next_page_token": page["next_page_token"],
            "complete": page["next_page_token"] is None,
            "raw": page["raw"],
        }

    def fetch_supporting_samples(
        self,
        data_type: str = "heart-rate",
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = 1000,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch and normalize one heart-rate or distance telemetry page."""

        canonical = _canonical_data_type(data_type)
        if canonical == "exercise":
            raise ValueError("fetch_supporting_samples is for telemetry data types, not exercise")
        page = self.list_data_points(
            canonical,
            start_time,
            end_time,
            page_token=page_token,
            page_size=page_size,
            filter_expression=filter_expression,
        )
        samples = [_normalize_sample(canonical, point) for point in page["data_points"]]
        return {
            "data_type": canonical,
            "samples": samples,
            "records": samples,
            "next_page_token": page["next_page_token"],
            "complete": page["next_page_token"] is None,
            "raw": page["raw"],
        }

    def export_exercise_tcx(
        self,
        exercise_id: str,
        *,
        partial_data: bool = False,
    ) -> dict[str, Any]:
        """Download the documented TCX route for one exercise data point."""

        identifier = _resource_id(exercise_id)
        params: dict[str, Any] = {"alt": "media"}
        if partial_data:
            params["partialData"] = "true"
        response = self._request(
            "GET",
            f"/users/me/dataTypes/exercise/dataPoints/{quote(identifier, safe='_-')}:exportExerciseTcx",
            params=params,
            binary=True,
        )
        raw_bytes = response.content
        content_type = response.headers.get("Content-Type", "").split(";", 1)[0].strip().lower()
        if "json" in content_type or raw_bytes.lstrip().startswith(b"{"):
            try:
                raw_json = response.json()
            except ValueError as exc:
                raise GoogleHealthResponseError("Google Health route response was invalid JSON") from exc
            if not isinstance(raw_json, dict):
                raise GoogleHealthResponseError("Google Health route JSON must be an object", details=raw_json)
            tcx_data = raw_json.get("tcxData")
            route_bytes = tcx_data.encode("utf-8") if isinstance(tcx_data, str) else b""
            return {
                "exercise_id": identifier,
                "points": _parse_tcx_points(route_bytes) if route_bytes else [],
                "raw": route_bytes,
                "raw_provider_json": deepcopy(raw_json),
                "content_type": content_type or "application/json",
            }
        return {
            "exercise_id": identifier,
            "points": _parse_tcx_points(raw_bytes),
            "raw": raw_bytes,
            "content_type": content_type or "application/tcx+xml",
        }

    def fetch_activity(
        self,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        include_samples: bool = True,
        include_routes: bool = False,
        supporting_data_types: tuple[str, ...] = ("heart-rate", "distance"),
        page_size: int | None = None,
        sample_page_size: int | None = 1000,
        max_pages: int = 100,
    ) -> dict[str, Any]:
        """Fetch all requested pages while retaining partial results and errors.

        ``coverage.complete`` is false if any page, telemetry stream, or route
        export could not be retrieved.  When no start bound is supplied,
        ``coverage.oldest_returned`` reports the oldest record actually seen;
        it does not claim that the account has no older history.
        """

        if max_pages <= 0:
            raise ValueError("max_pages must be positive")
        errors: list[dict[str, Any]] = []
        sessions: list[dict[str, Any]] = []
        raw_pages: dict[str, Any] = {"sessions": [], "samples": {}, "routes": []}
        pages: dict[str, int] = {"sessions": 0, "samples": 0, "routes": 0}
        complete: dict[str, bool] = {"sessions": False, "samples": not include_samples, "routes": not include_routes}

        session_token: str | None = None
        for _ in range(max_pages):
            try:
                page = self.fetch_activity_sessions(
                    start_time,
                    end_time,
                    page_token=session_token,
                    page_size=page_size,
                )
            except GoogleHealthError as exc:
                errors.append(self._error_record("sessions", exc))
                break
            pages["sessions"] += 1
            sessions.extend(page["sessions"])
            raw_pages["sessions"].append(page["raw"])
            session_token = page["next_page_token"]
            if session_token is None:
                complete["sessions"] = True
                break
        else:
            errors.append({"stream": "sessions", "error": "page_limit_exceeded", "message": f"more than {max_pages} pages"})

        # A bounded window around returned sessions keeps a no-argument cold
        # load from asking every telemetry point in the account.  The bound is
        # only an optimization; an explicit caller range always wins.
        sample_start = start_time
        sample_end = end_time
        if sample_start is None and sample_end is None and sessions:
            starts = [session.get("started_at") for session in sessions if session.get("started_at")]
            ends = [session.get("ended_at") for session in sessions if session.get("ended_at")]
            if starts:
                sample_start = min(starts)
            if ends:
                sample_end = max(ends)

        samples: dict[str, list[dict[str, Any]]] = {}
        if include_samples:
            complete["samples"] = True
            for requested_type in supporting_data_types:
                canonical = _canonical_data_type(requested_type)
                if canonical == "exercise":
                    raise ValueError("supporting_data_types cannot contain exercise")
                stream_samples: list[dict[str, Any]] = []
                stream_raw: list[Any] = []
                token: str | None = None
                stream_complete = False
                for _ in range(max_pages):
                    try:
                        page = self.fetch_supporting_samples(
                            canonical,
                            sample_start,
                            sample_end,
                            page_token=token,
                            page_size=sample_page_size,
                        )
                    except GoogleHealthError as exc:
                        errors.append(self._error_record(canonical, exc))
                        break
                    pages["samples"] += 1
                    stream_samples.extend(page["samples"])
                    stream_raw.append(page["raw"])
                    token = page["next_page_token"]
                    if token is None:
                        stream_complete = True
                        break
                else:
                    errors.append({"stream": canonical, "error": "page_limit_exceeded", "message": f"more than {max_pages} pages"})
                samples[canonical] = stream_samples
                raw_pages["samples"][canonical] = stream_raw
                complete["samples"] = complete["samples"] and stream_complete

        routes: list[dict[str, Any]] = []
        if include_routes:
            complete["routes"] = True
            for session in sessions:
                if not session.get("has_gps"):
                    continue
                resource_name = session.get("resource_name") or session.get("id")
                try:
                    route = self.export_exercise_tcx(str(resource_name))
                except (GoogleHealthError, ValueError) as exc:
                    if isinstance(exc, GoogleHealthError):
                        errors.append(self._error_record("route", exc, resource_name=resource_name))
                    else:
                        errors.append({"stream": "route", "resource_name": resource_name, "error": str(exc)})
                    complete["routes"] = False
                    continue
                pages["routes"] += 1
                routes.append(route)
                raw_pages["routes"].append(route.get("raw"))

        returned_times: list[datetime] = []
        for session in sessions:
            for key in ("started_at", "ended_at"):
                parsed = _parse_timestamp(session.get(key))
                if parsed is not None:
                    returned_times.append(parsed)
        for stream in samples.values():
            for sample in stream:
                for key in ("timestamp", "start_time", "end_time"):
                    parsed = _parse_timestamp(sample.get(key))
                    if parsed is not None:
                        returned_times.append(parsed)
        oldest = min(returned_times).isoformat().replace("+00:00", "Z") if returned_times else None
        newest = max(returned_times).isoformat().replace("+00:00", "Z") if returned_times else None
        requested_start = _format_filter_time(start_time, civil=False) if start_time is not None else None
        requested_end = _format_filter_time(end_time, civil=False) if end_time is not None else None
        return {
            "sessions": sessions,
            "samples": samples,
            "routes": routes,
            "coverage": {
                "requested_start": requested_start,
                "requested_end": requested_end,
                "oldest_returned": oldest,
                "newest_returned": newest,
                "pages": pages,
                "record_counts": {
                    "sessions": len(sessions),
                    "samples": {key: len(value) for key, value in samples.items()},
                    "routes": len(routes),
                },
                "sessions_complete": complete["sessions"],
                "samples_complete": complete["samples"],
                "routes_complete": complete["routes"],
                "complete": all(complete.values()) and not errors,
            },
            "errors": errors,
            "raw": raw_pages,
        }

    # ``sync_activity`` is a descriptive alias for route owners that call the
    # aggregate operation from a background sync job.
    sync_activity = fetch_activity

    @staticmethod
    def _error_record(stream: str, error: GoogleHealthError, **extra: Any) -> dict[str, Any]:
        record: dict[str, Any] = {
            "stream": stream,
            "error": error.__class__.__name__,
            "message": str(error),
        }
        if error.status_code is not None:
            record["status_code"] = error.status_code
        if error.retry_after is not None:
            record["retry_after"] = error.retry_after
        if error.details is not None:
            record["details"] = deepcopy(error.details)
        record.update(extra)
        return record


__all__ = [
    "DEFAULT_GOOGLE_HEALTH_SCOPES",
    "GOOGLE_AUTHORIZATION_ENDPOINT",
    "GOOGLE_HEALTH_BASE_URL",
    "GOOGLE_TOKEN_ENDPOINT",
    "GOOGLEHEALTH_ACTIVITY_SCOPE",
    "GOOGLEHEALTH_HEALTH_METRICS_SCOPE",
    "GOOGLEHEALTH_LOCATION_SCOPE",
    "GoogleHealthAuthError",
    "GoogleHealthClient",
    "GoogleHealthError",
    "GoogleHealthRateLimitError",
    "GoogleHealthResponseError",
    "GoogleHealthTimeoutError",
    "GoogleHealthTransportError",
    "build_authorization_url",
    "exchange_code",
    "refresh_token",
]
