"""Small, transport-only client for the Google Health API.

The Google Health API is the current Fitbit and Pixel device data surface.  A
caller supplies an access token that it obtained through its own OAuth flow;
this module deliberately has no database, user model, or FastAPI ownership.

Only the documented Health API v4 endpoints used by Runwise are exposed here.
In particular, this module does not accept arbitrary URLs or fall back to the
legacy Fitbit Web API.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date, datetime, timedelta, timezone
import math
import re
import time
from typing import Any, Callable, Mapping
from urllib.parse import quote, urlencode
import xml.etree.ElementTree as ET

import httpx


GOOGLE_AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_HEALTH_BASE_URL = "https://health.googleapis.com/v4"

GOOGLEHEALTH_ACTIVITY_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly"
)
GOOGLEHEALTH_HEALTH_METRICS_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly"
)
GOOGLEHEALTH_LOCATION_SCOPE = (
    "https://www.googleapis.com/auth/googlehealth.location.readonly"
)

# Runwise needs all three read scopes for sessions, continuous heart-rate
# samples, and route export respectively.  They are kept as a tuple so the
# consent URL has a stable, testable order.
DEFAULT_GOOGLE_HEALTH_SCOPES = (
    GOOGLEHEALTH_ACTIVITY_SCOPE,
    GOOGLEHEALTH_HEALTH_METRICS_SCOPE,
    GOOGLEHEALTH_LOCATION_SCOPE,
)

_SUPPORTED_DATA_TYPES = frozenset(
    {
        "exercise",
        "heart-rate",
        "distance",
        "steps",
        "active-energy-burned",
        "active-zone-minutes",
    }
)
_DATA_TYPE_ALIASES = {
    "heart_rate": "heart-rate",
    "heart-rate": "heart-rate",
    "distance": "distance",
    "steps": "steps",
    "active_energy_burned": "active-energy-burned",
    "active-energy-burned": "active-energy-burned",
    "active_zone_minutes": "active-zone-minutes",
    "active-zone-minutes": "active-zone-minutes",
    "exercise": "exercise",
}


class GoogleHealthError(RuntimeError):
    """Base error raised by the OAuth or Google Health transport."""

    def __init__(
        self,
        message: str,
        *,
        status_code: int | None = None,
        details: Any = None,
        retry_after: float | None = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.details = details
        self.retry_after = retry_after


class GoogleHealthAuthError(GoogleHealthError):
    """The OAuth authorization-code or refresh-token request was rejected."""


class GoogleHealthRateLimitError(GoogleHealthError):
    """The API still returned 429 after the bounded retry budget."""


class GoogleHealthTimeoutError(GoogleHealthError):
    """The API did not respond within the configured timeout and retry budget."""


class GoogleHealthTransportError(GoogleHealthError):
    """A non-timeout network error prevented a request from completing."""


class GoogleHealthResponseError(GoogleHealthError):
    """The provider returned an invalid JSON or media response."""


def _required_text(value: str, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field_name} must be a non-empty string")
    return value.strip()


def build_authorization_url(
    client_id: str,
    redirect_uri: str,
    state: str,
    code_challenge: str,
) -> str:
    """Build the Google OAuth 2.0 authorization URL used by Runwise.

    ``code_challenge`` is a PKCE S256 challenge generated by the route owner.
    The matching verifier is accepted by :func:`exchange_code`.  ``state`` is
    always carried through so the route owner can validate CSRF protection.
    """

    params = {
        "client_id": _required_text(client_id, "client_id"),
        "redirect_uri": _required_text(redirect_uri, "redirect_uri"),
        "response_type": "code",
        "scope": " ".join(DEFAULT_GOOGLE_HEALTH_SCOPES),
        "access_type": "offline",
        "prompt": "consent",
        "state": _required_text(state, "state"),
        "code_challenge": _required_text(code_challenge, "code_challenge"),
        "code_challenge_method": "S256",
    }
    return f"{GOOGLE_AUTHORIZATION_ENDPOINT}?{urlencode(params)}"


def _token_post(
    data: Mapping[str, str],
    *,
    http_client: httpx.Client | None,
    timeout: float,
) -> dict[str, Any]:
    client = http_client or httpx.Client(timeout=timeout)
    try:
        try:
            response = client.post(
                GOOGLE_TOKEN_ENDPOINT,
                data=dict(data),
                headers={"Accept": "application/json"},
                timeout=timeout,
            )
        except httpx.TimeoutException as exc:
            raise GoogleHealthTimeoutError(
                "Google OAuth token request timed out"
            ) from exc
        except httpx.TransportError as exc:
            raise GoogleHealthTransportError(
                "Google OAuth token request failed"
            ) from exc

        try:
            payload = response.json()
        except ValueError as exc:
            payload = response.text[:2000]
            raise GoogleHealthResponseError(
                "Google OAuth returned a non-JSON response",
                status_code=response.status_code,
                details=payload,
            ) from exc
        if response.status_code < 200 or response.status_code >= 300:
            message = "Google OAuth token request was rejected"
            if isinstance(payload, Mapping):
                message = str(payload.get("error_description") or payload.get("error") or message)
            raise GoogleHealthAuthError(
                message,
                status_code=response.status_code,
                details=payload,
            )
        if not isinstance(payload, dict):
            raise GoogleHealthResponseError(
                "Google OAuth response must be a JSON object",
                status_code=response.status_code,
                details=payload,
            )
        return payload
    finally:
        if http_client is None:
            client.close()


def exchange_code(
    code: str,
    client_id: str,
    redirect_uri: str,
    client_secret: str | None = None,
    code_verifier: str | None = None,
    *,
    http_client: httpx.Client | None = None,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """Exchange an authorization code for Google OAuth tokens.

    The route owner should persist the returned ``refresh_token`` securely.
    ``client_secret`` is optional to support public PKCE clients; confidential
    clients should supply it.  The positional order is ``code, client_id,
    redirect_uri, client_secret, code_verifier`` and all arguments can also be
    supplied by keyword.
    """

    body: dict[str, str] = {
        "code": _required_text(code, "code"),
        "client_id": _required_text(client_id, "client_id"),
        "redirect_uri": _required_text(redirect_uri, "redirect_uri"),
        "grant_type": "authorization_code",
    }
    if client_secret is not None:
        body["client_secret"] = _required_text(client_secret, "client_secret")
    if code_verifier is not None:
        body["code_verifier"] = _required_text(code_verifier, "code_verifier")
    return _token_post(body, http_client=http_client, timeout=timeout)


def refresh_token(
    token: str,
    client_id: str,
    client_secret: str | None = None,
    *,
    http_client: httpx.Client | None = None,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """Refresh a Google OAuth access token using an offline refresh token."""

    body: dict[str, str] = {
        "refresh_token": _required_text(token, "refresh_token"),
        "client_id": _required_text(client_id, "client_id"),
        "grant_type": "refresh_token",
    }
    if client_secret is not None:
        body["client_secret"] = _required_text(client_secret, "client_secret")
    return _token_post(body, http_client=http_client, timeout=timeout)


def _canonical_data_type(data_type: str) -> str:
    if not isinstance(data_type, str):
        raise ValueError("data_type must be a string")
    canonical = _DATA_TYPE_ALIASES.get(data_type.strip().lower(), data_type.strip().lower())
    if canonical not in _SUPPORTED_DATA_TYPES:
        allowed = ", ".join(sorted(_SUPPORTED_DATA_TYPES))
        raise ValueError(f"unsupported Google Health data_type {data_type!r}; use one of: {allowed}")
    return canonical


def _parse_duration(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        number = float(value)
        return number if math.isfinite(number) and number >= 0 else None
    if isinstance(value, str):
        match = re.fullmatch(r"\s*([0-9]+(?:\.[0-9]+)?)s\s*", value)
        if match:
            return float(match.group(1))
    return None


def _parse_utc_offset_seconds(value: Any) -> int | None:
    """Parse a Google duration-style UTC offset within one civil day."""

    if isinstance(value, str):
        match = re.fullmatch(r"\s*([+-]?[0-9]+(?:\.[0-9]+)?)s\s*", value)
        if not match:
            return None
        value = match.group(1)
    number = _parse_numeric(value)
    if number is None or abs(number) > 86_400:
        return None
    return int(round(number))


def _parse_numeric(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _parse_timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip()
    if raw.endswith("Z"):
        raw = f"{raw[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _duration_between(start: Any, end: Any) -> float | None:
    first = _parse_timestamp(start)
    last = _parse_timestamp(end)
    if first is None or last is None:
        return None
    seconds = (last - first).total_seconds()
    return seconds if math.isfinite(seconds) and seconds >= 0 else None


def _format_filter_time(value: date | datetime | str, *, civil: bool) -> str:
    if isinstance(value, datetime):
        current = value
        if civil:
            if current.tzinfo is not None:
                current = current.astimezone().replace(tzinfo=None)
            return current.isoformat(timespec="seconds")
        if current.tzinfo is None:
            current = current.replace(tzinfo=timezone.utc)
        current = current.astimezone(timezone.utc)
        return current.isoformat(timespec="seconds").replace("+00:00", "Z")
    if isinstance(value, date):
        return value.isoformat() if civil else value.isoformat() + "T00:00:00Z"
    current = value.strip()
    if not current or '"' in current:
        raise ValueError("time filter values must be non-empty and cannot contain quotes")
    if not civil and re.fullmatch(r"\d{4}-\d{2}-\d{2}", current):
        return date.fromisoformat(current).isoformat() + "T00:00:00Z"
    return current


def _date_only_bound(value: date | datetime | str | None) -> date | None:
    """Return a date only for an ISO date literal without a time component."""

    if isinstance(value, datetime):
        return None
    if isinstance(value, date):
        return value
    if isinstance(value, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}", value.strip()):
        try:
            return date.fromisoformat(value.strip())
        except ValueError:
            return None
    return None


def _calendar_filter_windows(
    start_time: date | datetime | str | None,
    end_time: date | datetime | str | None,
) -> list[tuple[date | datetime | str, date | datetime | str]]:
    """Split date-only ranges into at most one-calendar-month requests.

    Fitbit-origin records have returned a sparse/generic ``WORKOUT`` summary
    for broad exercise queries and a richer running summary for narrower
    ranges.  Keeping each request to one calendar month makes the import
    deterministic and bounds the provider's reconciliation window.  Datetime
    ranges retain the existing single-request behavior because splitting them
    would require choosing a civil timezone that the API does not expose.
    """

    first = _date_only_bound(start_time)
    last = _date_only_bound(end_time)
    if first is None or last is None or last <= first:
        if start_time is None and end_time is None:
            return [(None, None)]  # type: ignore[list-item]
        return [(start_time, end_time)]  # type: ignore[list-item]
    windows: list[tuple[date, date]] = []
    cursor = first
    while cursor < last:
        if cursor.month == 12:
            month_end = date(cursor.year + 1, 1, 1)
        else:
            month_end = date(cursor.year, cursor.month + 1, 1)
        boundary = min(month_end, last)
        windows.append((cursor, boundary))
        cursor = boundary
    return windows


def _build_filter(
    data_type: str,
    start_time: date | datetime | str | None,
    end_time: date | datetime | str | None,
) -> str | None:
    if start_time is None and end_time is None:
        return None
    if data_type == "exercise":
        field = "exercise.interval.civil_start_time"
        civil = True
    elif data_type == "heart-rate":
        field = "heart_rate.sample_time.physical_time"
        civil = False
    else:
        snake_name = data_type.replace("-", "_")
        field = f"{snake_name}.interval.start_time"
        civil = False
    terms: list[str] = []
    if start_time is not None:
        terms.append(f'{field} >= "{_format_filter_time(start_time, civil=civil)}"')
    if end_time is not None:
        terms.append(f'{field} < "{_format_filter_time(end_time, civil=civil)}"')
    return " AND ".join(terms)


def _parse_retry_after(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        delay = float(value)
    except (TypeError, ValueError):
        return None
    return delay if math.isfinite(delay) and delay >= 0 else None


def _error_details(response: httpx.Response) -> Any:
    try:
        return response.json()
    except ValueError:
        return response.text[:2000]


def _resource_id(exercise_id: str) -> str:
    """Validate an exercise ID or its documented resource name."""

    raw = _required_text(exercise_id, "exercise_id")
    resource = re.fullmatch(r"users/[A-Za-z0-9_-]+/dataTypes/exercise/dataPoints/([A-Za-z0-9_-]{1,200})", raw)
    if resource:
        raw = resource.group(1)
    if "/" in raw or ":" in raw or not re.fullmatch(r"[A-Za-z0-9_-]{1,200}", raw):
        raise ValueError("exercise_id must be an ID or an exercise resource name")
    return raw


def _last_resource_component(name: Any) -> str | None:
    if not isinstance(name, str) or not name:
        return None
    return name.rstrip("/").split("/")[-1] or None


def _normalize_split(split: Mapping[str, Any], *, source: str = "splitSummaries") -> dict[str, Any]:
    """Normalize a provider split while retaining every provider field.

    Google has emitted both ``splits`` and ``splitSummaries`` in real Fitbit
    records.  They describe the same kind of lap but are distinct fields in
    the current schema, so the source is carried through when both are
    present.  ``raw`` remains the authoritative lossless provider object.
    """

    metrics = split.get("metricsSummary") or split.get("metrics_summary")
    metrics = metrics if isinstance(metrics, Mapping) else {}
    distance_mm = _parse_numeric(metrics.get("distanceMillimeters") or metrics.get("distance_millimeters"))
    start_time = split.get("startTime") or split.get("start_time")
    end_time = split.get("endTime") or split.get("end_time")
    active_duration = _parse_duration(split.get("activeDuration") or split.get("active_duration"))
    return {
        "source": source,
        "start_time": start_time,
        "end_time": end_time,
        "active_duration_seconds": active_duration,
        "elapsed_seconds": _duration_between(start_time, end_time),
        "distance_m": distance_mm / 1000.0 if distance_mm is not None else None,
        "distance_km": distance_mm / 1_000_000.0 if distance_mm is not None else None,
        "split_type": split.get("splitType") or split.get("split_type"),
        "metrics_summary": deepcopy(dict(metrics)),
        "raw": deepcopy(dict(split)),
    }


_NESTED_EXERCISE_COLLECTIONS = (
    "children",
    "childExercises",
    "activities",
    "activitySegments",
    "segments",
    "laps",
)


def _component_time(component: Mapping[str, Any], key: str) -> Any:
    interval = component.get("interval")
    if isinstance(interval, Mapping):
        value = interval.get(key)
        if value is not None:
            return value
    snake_key = key[0].lower() + re.sub(r"([A-Z])", lambda match: "_" + match.group(1).lower(), key[1:])
    return component.get(key) or component.get(snake_key)


def _component_distance_m(component: Mapping[str, Any]) -> float | None:
    metrics = component.get("metricsSummary") or component.get("metrics_summary")
    metrics = metrics if isinstance(metrics, Mapping) else {}
    for key, divisor in (
        ("distanceMillimeters", 1000.0),
        ("distance_millimeters", 1000.0),
        ("distanceMeters", 1.0),
        ("distance_meters", 1.0),
        ("distanceM", 1.0),
        ("distance_m", 1.0),
        ("distanceKm", 0.001),
        ("distance_km", 0.001),
    ):
        number = _parse_numeric(metrics.get(key))
        if number is not None:
            return number / divisor if divisor != 0 else None
    for key, divisor in (
        ("distanceMillimeters", 1000.0),
        ("distance_millimeters", 1000.0),
        ("distanceMeters", 1.0),
        ("distance_meters", 1.0),
        ("distanceM", 1.0),
        ("distance_m", 1.0),
        ("distanceKm", 0.001),
        ("distance_km", 0.001),
        ("distance", 1.0),
    ):
        number = _parse_numeric(component.get(key))
        if number is not None:
            return number / divisor if divisor != 0 else None
    return None


def _normalize_exercise_component(
    component: Mapping[str, Any],
    *,
    source: str,
    index: int,
) -> dict[str, Any]:
    """Normalize an undocumented nested workout component generically.

    ``children``/``segments`` are not part of the current Google Health
    ``Exercise`` schema, but Fitbit migrations and connector wrappers have
    returned nested activity objects.  Keeping a small normalized projection
    plus the exact raw object lets callers inspect those records without
    dropping custom fields.
    """

    start_time = _component_time(component, "startTime")
    end_time = _component_time(component, "endTime")
    activity_type = (
        component.get("exerciseType")
        or component.get("exercise_type")
        or component.get("activityType")
        or component.get("activity_type")
        or component.get("sport")
        or component.get("type")
    )
    display_name = component.get("displayName") or component.get("display_name") or component.get("title")
    return {
        "source": source,
        "index": index,
        "activity_type": activity_type,
        "display_name": display_name,
        "started_at": start_time,
        "ended_at": end_time,
        "elapsed_seconds": _duration_between(start_time, end_time),
        "active_duration_seconds": _parse_duration(
            component.get("activeDuration") or component.get("active_duration")
        ),
        "distance_m": _component_distance_m(component),
        "raw": deepcopy(dict(component)),
    }


def _normalize_nested_exercise_collections(exercise: Mapping[str, Any]) -> dict[str, list[dict[str, Any]]]:
    normalized: dict[str, list[dict[str, Any]]] = {}
    for collection_name in _NESTED_EXERCISE_COLLECTIONS:
        values = exercise.get(collection_name)
        if not isinstance(values, list):
            continue
        normalized[collection_name] = [
            _normalize_exercise_component(item, source=collection_name, index=index)
            for index, item in enumerate(values)
            if isinstance(item, Mapping)
        ]
    return normalized


def _normalize_session(point: Mapping[str, Any]) -> dict[str, Any]:
    exercise = point.get("exercise")
    exercise = exercise if isinstance(exercise, Mapping) else {}
    interval = exercise.get("interval")
    interval = interval if isinstance(interval, Mapping) else {}
    metrics = exercise.get("metricsSummary")
    metrics = metrics if isinstance(metrics, Mapping) else {}
    metadata = exercise.get("exerciseMetadata")
    metadata = metadata if isinstance(metadata, Mapping) else {}
    name = point.get("name")
    start_time = interval.get("startTime")
    end_time = interval.get("endTime")
    distance_mm = _parse_numeric(metrics.get("distanceMillimeters"))
    distance_m = distance_mm / 1000.0 if distance_mm is not None else None
    active_duration = _parse_duration(exercise.get("activeDuration"))
    elapsed = _duration_between(start_time, end_time)
    average_hr = _parse_numeric(metrics.get("averageHeartRateBeatsPerMinute"))
    if average_hr is not None and average_hr.is_integer():
        average_hr = int(average_hr)
    default_name = exercise.get("displayName") or exercise.get("exerciseType") or "Exercise"
    normalized_splits: list[dict[str, Any]] = []
    for split_source in ("splitSummaries", "splits"):
        splits = exercise.get(split_source)
        if isinstance(splits, list):
            normalized_splits.extend(
                _normalize_split(split, source=split_source)
                for split in splits
                if isinstance(split, Mapping)
            )
    events = exercise.get("exerciseEvents")
    normalized_events = [deepcopy(dict(event)) for event in events if isinstance(event, Mapping)] if isinstance(events, list) else []
    nested = _normalize_nested_exercise_collections(exercise)
    component_distances = [
        component.get("distance_m")
        for collection in nested.values()
        for component in collection
        if isinstance(component.get("distance_m"), (int, float))
    ]
    if distance_m is None and component_distances:
        distance_m = sum(float(value) for value in component_distances)
    if elapsed is None:
        component_times = [
            (component.get("started_at"), component.get("ended_at"))
            for collection in nested.values()
            for component in collection
        ]
        starts = [_parse_timestamp(start) for start, _ in component_times]
        ends = [_parse_timestamp(end) for _, end in component_times]
        starts = [value for value in starts if value is not None]
        ends = [value for value in ends if value is not None]
        if starts and ends:
            elapsed = (max(ends) - min(starts)).total_seconds()
    component_aliases = {
        key: values
        for key, values in nested.items()
        if key in {"children", "childExercises", "activities", "activitySegments", "segments", "laps"}
    }
    raw = deepcopy(dict(point))
    source_utc_offset_seconds = _parse_utc_offset_seconds(
        interval.get("startUtcOffset") or interval.get("start_utc_offset")
    )
    normalized = {
        "provider": "google_health",
        "data_type": "exercise",
        "id": name,
        "source_id": name,
        "provider_id": _last_resource_component(name),
        "resource_name": name,
        "title": default_name,
        "display_name": exercise.get("displayName"),
        "activity_type": exercise.get("exerciseType"),
        "started_at": start_time,
        "ended_at": end_time,
        "source_utc_offset_seconds": source_utc_offset_seconds,
        "elapsed_seconds": elapsed,
        "duration_seconds": elapsed,
        "active_duration_seconds": active_duration,
        "distance_m": distance_m,
        "distance_km": distance_m / 1000.0 if distance_m is not None else None,
        "average_hr_bpm": average_hr,
        "avg_hr": average_hr,
        "average_speed_mps": (
            _parse_numeric(metrics.get("averageSpeedMillimetersPerSecond")) / 1000.0
            if _parse_numeric(metrics.get("averageSpeedMillimetersPerSecond")) is not None
            else None
        ),
        "average_pace_seconds_per_meter": _parse_numeric(metrics.get("averagePaceSecondsPerMeter")),
        "has_gps": metadata.get("hasGps"),
        "exercise_events": normalized_events,
        "splits": normalized_splits,
        "metrics_summary": deepcopy(dict(metrics)),
        "exercise_metadata": deepcopy(dict(metadata)),
        "notes": exercise.get("notes"),
        "data_source": deepcopy(dict(point.get("dataSource"))) if isinstance(point.get("dataSource"), Mapping) else {},
        "raw": raw,
    }
    normalized.update(component_aliases)
    return normalized


def _session_identity(session: Mapping[str, Any]) -> str:
    """Return the stable provider identity used to merge overlapping pages."""

    for key in ("provider_id", "source_id", "id", "resource_name"):
        value = session.get(key)
        if isinstance(value, str) and value.strip():
            return f"{key}:{value.strip()}"
    # A malformed provider page should still be retained, but records without
    # an identity cannot be safely merged with one another.
    fallback = (
        session.get("started_at"),
        session.get("ended_at"),
        session.get("activity_type"),
        session.get("title"),
    )
    return "fallback:" + "|".join(str(value or "") for value in fallback)


def _session_richness(session: Mapping[str, Any]) -> tuple[int, ...]:
    """Rank duplicate exercise summaries by fields useful to Runwise.

    The same Fitbit-origin exercise ID can be returned as a generic,
    distance-less ``WORKOUT`` for a broad query and as a populated ``RUNNING``
    record for a one-month query.  Distance is the strongest signal, followed
    by the concrete activity type, GPS metadata, splits, and other detail.
    """

    distance = _parse_numeric(session.get("distance_m"))
    activity = str(session.get("activity_type") or "").strip().upper()
    known_type = bool(activity and activity not in {"WORKOUT", "EXERCISE", "UNKNOWN"})
    metrics = session.get("metrics_summary")
    splits = session.get("splits")
    events = session.get("exercise_events")
    components = sum(
        len(value)
        for key in _NESTED_EXERCISE_COLLECTIONS
        for value in [session.get(key)]
        if isinstance(value, list)
    )
    raw = session.get("raw")
    return (
        int(distance is not None and distance > 0),
        int(known_type),
        int(session.get("has_gps") is True),
        min(len(splits), 100) if isinstance(splits, list) else 0,
        min(components, 100),
        min(len(events), 100) if isinstance(events, list) else 0,
        min(len(metrics), 100) if isinstance(metrics, Mapping) else 0,
        int(session.get("active_duration_seconds") is not None),
        int(session.get("duration_seconds") is not None),
        min(len(raw), 100) if isinstance(raw, Mapping) else 0,
    )


def _merge_session_pages(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Dedupe overlapping exercise pages while preferring richer summaries."""

    selected: dict[str, tuple[dict[str, Any], int]] = {}
    for position, record in enumerate(records):
        if not isinstance(record, dict):
            continue
        identity = _session_identity(record)
        current = selected.get(identity)
        if current is None or _session_richness(record) > _session_richness(current[0]):
            selected[identity] = (record, position)
    ordered = list(selected.values())

    def sort_key(item: tuple[dict[str, Any], int]) -> tuple[int, float, int]:
        timestamp = _parse_timestamp(item[0].get("started_at"))
        return (
            int(timestamp is not None),
            timestamp.timestamp() if timestamp is not None else float("-inf"),
            -item[1],
        )

    ordered.sort(key=sort_key, reverse=True)
    return [record for record, _ in ordered]


def _normalize_sample(data_type: str, point: Mapping[str, Any]) -> dict[str, Any]:
    raw = deepcopy(dict(point))
    payload = point.get(data_type.replace("-", ""))
    if data_type == "heart-rate":
        payload = point.get("heartRate")
        payload = payload if isinstance(payload, Mapping) else {}
        sample_time = payload.get("sampleTime")
        sample_time = sample_time if isinstance(sample_time, Mapping) else {}
        bpm = _parse_numeric(payload.get("beatsPerMinute"))
        if bpm is not None and bpm.is_integer():
            bpm = int(bpm)
        return {
            "provider": "google_health",
            "data_type": data_type,
            "id": point.get("name"),
            "timestamp": sample_time.get("physicalTime"),
            "sample_time": sample_time.get("physicalTime"),
            "heart_rate_bpm": bpm,
            "bpm": bpm,
            "metadata": deepcopy(payload.get("metadata")) if isinstance(payload.get("metadata"), Mapping) else {},
            "raw": raw,
        }
    if data_type in {"distance", "steps", "active-energy-burned", "active-zone-minutes"}:
        field_name = {
            "distance": "distance",
            "steps": "steps",
            "active-energy-burned": "activeEnergyBurned",
            "active-zone-minutes": "activeZoneMinutes",
        }[data_type]
        payload = point.get(field_name)
        payload = payload if isinstance(payload, Mapping) else {}
        interval = payload.get("interval")
        interval = interval if isinstance(interval, Mapping) else {}
        raw_value = payload.get("millimeters") if data_type == "distance" else payload.get("count")
        if data_type == "active-energy-burned":
            raw_value = payload.get("calories") or payload.get("caloriesKcal")
        if data_type == "active-zone-minutes":
            raw_value = payload.get("activeZoneMinutes")
        numeric_value = _parse_numeric(raw_value)
        if data_type == "distance" and numeric_value is not None:
            numeric_value = numeric_value / 1000.0
        return {
            "provider": "google_health",
            "data_type": data_type,
            "id": point.get("name"),
            "start_time": interval.get("startTime"),
            "end_time": interval.get("endTime"),
            "timestamp": interval.get("startTime"),
            "elapsed_seconds": _duration_between(interval.get("startTime"), interval.get("endTime")),
            "value": numeric_value,
            "distance_m": numeric_value if data_type == "distance" else None,
            "raw": raw,
        }
    return {
        "provider": "google_health",
        "data_type": data_type,
        "id": point.get("name"),
        "raw": raw,
    }


def _tcx_local_name(tag: Any) -> str:
    return str(tag).rsplit("}", 1)[-1]


def _tcx_metadata(element: ET.Element, *, skip: frozenset[str] = frozenset()) -> Any:
    """Convert a TCX node to a bounded, namespace-free metadata object.

    Trackpoints are deliberately excluded by callers because the normalized
    route already carries them as point records.  Every other child and
    attribute is retained, including extension fields from device vendors.
    Duplicate child names become arrays rather than silently overwriting one
    another.
    """

    result: dict[str, Any] = {
        str(key): str(value)
        for key, value in element.attrib.items()
        if _tcx_local_name(key) not in skip
    }
    children = [child for child in list(element) if _tcx_local_name(child.tag) not in skip]
    if not children:
        text = (element.text or "").strip()
        return text if text else result
    for child in children:
        key = _tcx_local_name(child.tag)
        value = _tcx_metadata(child, skip=skip)
        if key in result:
            existing = result[key]
            if not isinstance(existing, list):
                existing = [existing]
            existing.append(value)
            result[key] = existing
        else:
            result[key] = value
    return result


def _parse_tcx_trackpoint(element: ET.Element) -> dict[str, Any]:
    values: dict[str, Any] = {}
    for child in element.iter():
        key = _tcx_local_name(child.tag)
        if key == "HeartRateBpm":
            for value in child.iter():
                if _tcx_local_name(value.tag) == "Value":
                    try:
                        values["HeartRateBpm"] = float(value.text or "")
                    except (TypeError, ValueError):
                        pass
        if child is element or child.text is None:
            continue
        text = child.text.strip()
        if key in {"LatitudeDegrees", "LongitudeDegrees", "AltitudeMeters", "DistanceMeters"}:
            try:
                values[key] = float(text)
            except (TypeError, ValueError):
                values[key] = None
        elif key == "Time":
            values[key] = text
    lat = values.get("LatitudeDegrees")
    lon = values.get("LongitudeDegrees")
    return {
        "timestamp": values.get("Time"),
        "lat": lat,
        "lon": lon,
        "altitude_m": values.get("AltitudeMeters"),
        "heart_rate": values.get("HeartRateBpm"),
        "distance_m": values.get("DistanceMeters"),
        "raw": deepcopy(values),
    }


def _parse_tcx_document(raw_tcx: bytes) -> dict[str, Any]:
    """Parse route points plus TCX activity/lap hierarchy and metadata."""

    try:
        root = ET.fromstring(raw_tcx)
    except (ET.ParseError, TypeError) as exc:
        raise GoogleHealthResponseError("Google Health returned invalid TCX XML") from exc

    points: list[dict[str, Any]] = []
    activities: list[dict[str, Any]] = []
    laps: list[dict[str, Any]] = []
    seen_trackpoints: set[int] = set()
    activity_elements = [element for element in root.iter() if _tcx_local_name(element.tag) == "Activity"]
    for activity_index, activity in enumerate(activity_elements):
        sport = activity.attrib.get("Sport") or activity.attrib.get("sport")
        activity_id: Any = None
        for child in activity.iter():
            if _tcx_local_name(child.tag) == "Id" and (child.text or "").strip():
                activity_id = child.text.strip()
                break
        activity_laps: list[dict[str, Any]] = []
        lap_elements = [element for element in activity if _tcx_local_name(element.tag) == "Lap"]
        # Some exporters wrap Lap in a vendor node.  Include those while
        # keeping the direct-child result order stable.
        if not lap_elements:
            lap_elements = [element for element in activity.iter() if _tcx_local_name(element.tag) == "Lap"]
        for lap_index, lap in enumerate(lap_elements):
            trackpoint_elements = [
                element for element in lap.iter() if _tcx_local_name(element.tag) == "Trackpoint"
            ]
            lap_points: list[dict[str, Any]] = []
            for trackpoint in trackpoint_elements:
                seen_trackpoints.add(id(trackpoint))
                point = _parse_tcx_trackpoint(trackpoint)
                point["activity_index"] = activity_index
                point["lap_index"] = lap_index
                points.append(point)
                lap_points.append(point)
            start_time = lap.attrib.get("StartTime") or lap.attrib.get("startTime")
            if start_time is None:
                start_node = next(
                    (child for child in lap if _tcx_local_name(child.tag) in {"StartTime", "startTime"}),
                    None,
                )
                start_time = (start_node.text or "").strip() if start_node is not None else None
            total_time: float | None = None
            distance_m: float | None = None
            lap_metadata = _tcx_metadata(lap, skip=frozenset({"Track", "Trackpoint"}))
            if isinstance(lap_metadata, dict):
                distance_m = _parse_numeric(lap_metadata.get("DistanceMeters")) or distance_m
                total_time = _parse_numeric(lap_metadata.get("TotalTimeSeconds")) or total_time
            last_timestamp = next(
                (point.get("timestamp") for point in reversed(lap_points) if point.get("timestamp")),
                None,
            )
            end_time = last_timestamp
            if start_time is not None and total_time is not None:
                start_dt = _parse_timestamp(start_time)
                if start_dt is not None:
                    calculated_end = (start_dt + timedelta(seconds=total_time)).isoformat().replace("+00:00", "Z")
                    last_dt = _parse_timestamp(last_timestamp)
                    if last_dt is None or last_dt < start_dt + timedelta(seconds=total_time):
                        end_time = calculated_end
            if distance_m is None:
                point_distances = [
                    float(point["distance_m"])
                    for point in lap_points
                    if isinstance(point.get("distance_m"), (int, float))
                    and math.isfinite(float(point["distance_m"]))
                ]
                distance_m = max(point_distances) if point_distances else None
            lap_record = {
                "activity_index": activity_index,
                "lap_index": lap_index,
                "start_time": start_time,
                "end_time": end_time,
                "elapsed_seconds": total_time,
                "distance_m": distance_m,
                "calories": _parse_numeric(lap_metadata.get("Calories")) if isinstance(lap_metadata, dict) else None,
                "intensity": lap_metadata.get("Intensity") if isinstance(lap_metadata, dict) else None,
                "trigger_method": lap_metadata.get("TriggerMethod") if isinstance(lap_metadata, dict) else None,
                "metadata": deepcopy(lap_metadata) if isinstance(lap_metadata, dict) else {},
                "raw": deepcopy(lap_metadata),
            }
            laps.append(lap_record)
            activity_laps.append(lap_record)
        activity_metadata = _tcx_metadata(activity, skip=frozenset({"Lap", "Track", "Trackpoint"}))
        activities.append(
            {
                "activity_index": activity_index,
                "sport": sport,
                "id": activity_id,
                "laps": activity_laps,
                "metadata": deepcopy(activity_metadata) if isinstance(activity_metadata, dict) else {},
                "raw": deepcopy(activity_metadata),
            }
        )

    # A few exporters put Trackpoint elements outside Activity/Lap.  Keep
    # those points rather than silently dropping them.
    for element in root.iter():
        if _tcx_local_name(element.tag) != "Trackpoint" or id(element) in seen_trackpoints:
            continue
        points.append(_parse_tcx_trackpoint(element))

    distances = [
        float(lap["distance_m"])
        for lap in laps
        if isinstance(lap.get("distance_m"), (int, float)) and math.isfinite(float(lap["distance_m"]))
    ]
    total_distance = sum(distances) if distances else None
    if total_distance is None:
        point_distances = [
            float(point["distance_m"])
            for point in points
            if isinstance(point.get("distance_m"), (int, float)) and math.isfinite(float(point["distance_m"]))
        ]
        total_distance = max(point_distances) if point_distances else None
    durations = [
        float(lap["elapsed_seconds"])
        for lap in laps
        if isinstance(lap.get("elapsed_seconds"), (int, float)) and math.isfinite(float(lap["elapsed_seconds"]))
    ]
    point_times = [_parse_timestamp(point.get("timestamp")) for point in points]
    point_times = [value for value in point_times if value is not None]
    point_elapsed = (max(point_times) - min(point_times)).total_seconds() if len(point_times) >= 2 else None
    elapsed = sum(durations) if durations else point_elapsed
    return {
        "points": points,
        "laps": laps,
        "activities": activities,
        "activity_sports": [activity.get("sport") for activity in activities if activity.get("sport")],
        "total_distance_m": total_distance,
        "elapsed_seconds": elapsed,
    }


def _parse_tcx_points(raw_tcx: bytes) -> list[dict[str, Any]]:
    return _parse_tcx_document(raw_tcx)["points"]


class GoogleHealthClient:
    """Synchronous Google Health API v4 client with bounded retries.

    ``http_client`` is injectable for tests (for example an ``httpx.Client``
    using ``MockTransport``).  In production the client owns a normal
    ``httpx.Client`` and can be closed directly or through a context manager.
    ``max_retries`` counts retries after the initial request.
    """

    def __init__(
        self,
        access_token: str,
        *,
        http_client: httpx.Client | None = None,
        timeout: float = 15.0,
        max_retries: int = 2,
        backoff_base: float = 0.25,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        self.access_token = _required_text(access_token, "access_token")
        if timeout <= 0 or not math.isfinite(timeout):
            raise ValueError("timeout must be a finite positive number")
        if max_retries < 0:
            raise ValueError("max_retries cannot be negative")
        if backoff_base < 0 or not math.isfinite(backoff_base):
            raise ValueError("backoff_base must be finite and non-negative")
        self.timeout = float(timeout)
        self.max_retries = int(max_retries)
        self.backoff_base = float(backoff_base)
        self._sleep = sleep
        self._http_client = http_client or httpx.Client(timeout=self.timeout)
        self._owns_http_client = http_client is None

    def close(self) -> None:
        if self._owns_http_client:
            self._http_client.close()
            self._owns_http_client = False

    def __enter__(self) -> "GoogleHealthClient":
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        self.close()

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Mapping[str, Any] | None = None,
        binary: bool = False,
    ) -> httpx.Response:
        if not path.startswith("/users/me/"):
            raise ValueError("Google Health paths must use the fixed users/me API surface")
        url = f"{GOOGLE_HEALTH_BASE_URL}{path}"
        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Accept": "application/octet-stream" if binary else "application/json",
        }
        last_timeout: httpx.TimeoutException | None = None
        for attempt in range(self.max_retries + 1):
            try:
                response = self._http_client.request(
                    method,
                    url,
                    params=dict(params or {}),
                    headers=headers,
                    timeout=self.timeout,
                )
            except httpx.TimeoutException as exc:
                last_timeout = exc
                if attempt < self.max_retries:
                    self._sleep(min(5.0, self.backoff_base * (2**attempt)))
                    continue
                raise GoogleHealthTimeoutError(
                    "Google Health API request timed out"
                ) from exc
            except httpx.TransportError as exc:
                raise GoogleHealthTransportError(
                    "Google Health API request failed"
                ) from exc

            if response.status_code not in {429, 500, 502, 503, 504}:
                break
            if attempt >= self.max_retries:
                break
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            delay = retry_after if retry_after is not None else self.backoff_base * (2**attempt)
            self._sleep(min(5.0, max(0.0, delay)))

        if response.status_code == 429:
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            raise GoogleHealthRateLimitError(
                "Google Health API rate limit exceeded",
                status_code=429,
                details=_error_details(response),
                retry_after=retry_after,
            )
        if response.status_code < 200 or response.status_code >= 300:
            raise GoogleHealthError(
                f"Google Health API returned HTTP {response.status_code}",
                status_code=response.status_code,
                details=_error_details(response),
                retry_after=_parse_retry_after(response.headers.get("Retry-After")),
            )
        return response

    def _request_json(
        self,
        path: str,
        *,
        params: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        response = self._request("GET", path, params=params)
        try:
            payload = response.json()
        except ValueError as exc:
            raise GoogleHealthResponseError(
                "Google Health API returned a non-JSON response",
                status_code=response.status_code,
                details=response.text[:2000],
            ) from exc
        if not isinstance(payload, dict):
            raise GoogleHealthResponseError(
                "Google Health API list response must be a JSON object",
                status_code=response.status_code,
                details=payload,
            )
        return payload

    def list_data_points(
        self,
        data_type: str,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = None,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch one documented ``dataPoints.list`` page.

        Google orders list results by interval/sample start time descending.
        ``next_page_token`` in the returned dict must be supplied to the next
        call to continue historical retrieval.
        """

        canonical = _canonical_data_type(data_type)
        params: dict[str, Any] = {}
        if page_size is not None:
            if isinstance(page_size, bool) or not isinstance(page_size, int) or page_size <= 0:
                raise ValueError("page_size must be a positive integer")
            max_page_size = 25 if canonical == "exercise" else 10_000
            params["pageSize"] = min(page_size, max_page_size)
        if page_token is not None:
            params["pageToken"] = _required_text(page_token, "page_token")
        generated_filter = _build_filter(canonical, start_time, end_time)
        if filter_expression is not None:
            if not isinstance(filter_expression, str) or not filter_expression.strip():
                raise ValueError("filter_expression must be a non-empty string")
            params["filter"] = filter_expression.strip()
        elif generated_filter is not None:
            params["filter"] = generated_filter
        payload = self._request_json(
            f"/users/me/dataTypes/{canonical}/dataPoints",
            params=params,
        )
        points = payload.get("dataPoints")
        if points is None:
            points = []
        if not isinstance(points, list):
            raise GoogleHealthResponseError(
                "Google Health API response dataPoints must be an array",
                details=payload,
            )
        token = payload.get("nextPageToken")
        if token is not None and not isinstance(token, str):
            raise GoogleHealthResponseError(
                "Google Health API nextPageToken must be a string",
                details=payload,
            )
        return {
            "data_type": canonical,
            "data_points": [deepcopy(point) for point in points if isinstance(point, Mapping)],
            "next_page_token": token or None,
            "raw": deepcopy(payload),
        }

    def fetch_activity_sessions(
        self,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = 25,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch and normalize one ``exercise`` session page."""

        page = self.list_data_points(
            "exercise",
            start_time,
            end_time,
            page_token=page_token,
            page_size=page_size,
            filter_expression=filter_expression,
        )
        sessions = [_normalize_session(point) for point in page["data_points"]]
        return {
            "data_type": "exercise",
            "sessions": sessions,
            "data": sessions,
            "next_page_token": page["next_page_token"],
            "complete": page["next_page_token"] is None,
            "raw": page["raw"],
        }

    def fetch_supporting_samples(
        self,
        data_type: str = "heart-rate",
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        page_token: str | None = None,
        page_size: int | None = 1000,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Fetch and normalize one heart-rate or distance telemetry page."""

        canonical = _canonical_data_type(data_type)
        if canonical == "exercise":
            raise ValueError("fetch_supporting_samples is for telemetry data types, not exercise")
        page = self.list_data_points(
            canonical,
            start_time,
            end_time,
            page_token=page_token,
            page_size=page_size,
            filter_expression=filter_expression,
        )
        samples = [_normalize_sample(canonical, point) for point in page["data_points"]]
        return {
            "data_type": canonical,
            "samples": samples,
            "records": samples,
            "next_page_token": page["next_page_token"],
            "complete": page["next_page_token"] is None,
            "raw": page["raw"],
        }

    def export_exercise_tcx(
        self,
        exercise_id: str,
        *,
        partial_data: bool = False,
    ) -> dict[str, Any]:
        """Download the documented TCX route for one exercise data point."""

        identifier = _resource_id(exercise_id)
        params: dict[str, Any] = {"alt": "media"}
        if partial_data:
            params["partialData"] = "true"
        response = self._request(
            "GET",
            f"/users/me/dataTypes/exercise/dataPoints/{quote(identifier, safe='_-')}:exportExerciseTcx",
            params=params,
            binary=True,
        )
        raw_bytes = response.content
        content_type = response.headers.get("Content-Type", "").split(";", 1)[0].strip().lower()
        if "json" in content_type or raw_bytes.lstrip().startswith(b"{"):
            try:
                raw_json = response.json()
            except ValueError as exc:
                raise GoogleHealthResponseError("Google Health route response was invalid JSON") from exc
            if not isinstance(raw_json, dict):
                raise GoogleHealthResponseError("Google Health route JSON must be an object", details=raw_json)
            tcx_data = raw_json.get("tcxData")
            route_bytes = tcx_data.encode("utf-8") if isinstance(tcx_data, str) else b""
            parsed = _parse_tcx_document(route_bytes) if route_bytes else {
                "points": [],
                "laps": [],
                "activities": [],
                "activity_sports": [],
                "total_distance_m": None,
                "elapsed_seconds": None,
            }
            return {
                "exercise_id": identifier,
                "points": parsed["points"],
                "laps": parsed["laps"],
                "activities": parsed["activities"],
                "activity_sports": parsed["activity_sports"],
                "total_distance_m": parsed["total_distance_m"],
                "elapsed_seconds": parsed["elapsed_seconds"],
                "raw": route_bytes,
                "raw_provider_json": deepcopy(raw_json),
                "content_type": content_type or "application/json",
            }
        parsed = _parse_tcx_document(raw_bytes)
        return {
            "exercise_id": identifier,
            "points": parsed["points"],
            "laps": parsed["laps"],
            "activities": parsed["activities"],
            "activity_sports": parsed["activity_sports"],
            "total_distance_m": parsed["total_distance_m"],
            "elapsed_seconds": parsed["elapsed_seconds"],
            "raw": raw_bytes,
            "content_type": content_type or "application/tcx+xml",
        }

    def fetch_activity(
        self,
        start_time: date | datetime | str | None = None,
        end_time: date | datetime | str | None = None,
        *,
        include_samples: bool = True,
        include_routes: bool = False,
        supporting_data_types: tuple[str, ...] = ("heart-rate", "distance"),
        page_size: int | None = None,
        sample_page_size: int | None = 1000,
        max_pages: int = 100,
    ) -> dict[str, Any]:
        """Fetch all requested pages while retaining partial results and errors.

        ``coverage.complete`` is false if any page, telemetry stream, or route
        export could not be retrieved.  When no start bound is supplied,
        ``coverage.oldest_returned`` reports the oldest record actually seen;
        it does not claim that the account has no older history.
        """

        if max_pages <= 0:
            raise ValueError("max_pages must be positive")
        errors: list[dict[str, Any]] = []
        session_records: list[dict[str, Any]] = []
        raw_pages: dict[str, Any] = {"sessions": [], "samples": {}, "routes": []}
        pages: dict[str, int] = {"sessions": 0, "samples": 0, "routes": 0}
        complete: dict[str, bool] = {"sessions": False, "samples": not include_samples, "routes": not include_routes}

        # Exercise queries are intentionally split on calendar-month
        # boundaries.  Google Health has returned the same Fitbit exercise ID
        # as a sparse WORKOUT summary for a broad range and as a populated
        # RUNNING summary for a one-month range.  Each window is paginated
        # independently, then duplicate IDs are merged by richness below.
        session_windows = _calendar_filter_windows(start_time, end_time)
        session_window_status: list[dict[str, Any]] = []
        for window_start, window_end in session_windows:
            window_complete = False
            session_token: str | None = None
            seen_tokens: set[str] = set()
            window_context = {
                "window_start": _format_filter_time(window_start, civil=True) if window_start is not None else None,
                "window_end": _format_filter_time(window_end, civil=True) if window_end is not None else None,
            }
            for _ in range(max_pages):
                if session_token is not None:
                    if session_token in seen_tokens:
                        errors.append({"stream": "sessions", "error": "page_token_cycle", **window_context})
                        break
                    seen_tokens.add(session_token)
                try:
                    page = self.fetch_activity_sessions(
                        window_start,
                        window_end,
                        page_token=session_token,
                        page_size=page_size,
                    )
                except GoogleHealthError as exc:
                    errors.append(self._error_record("sessions", exc, **window_context))
                    break
                pages["sessions"] += 1
                session_records.extend(page["sessions"])
                raw_pages["sessions"].append(page["raw"])
                session_token = page["next_page_token"]
                if session_token is None:
                    window_complete = True
                    break
            else:
                errors.append(
                    {
                        "stream": "sessions",
                        "error": "page_limit_exceeded",
                        "message": f"more than {max_pages} pages",
                        **window_context,
                    }
                )
            session_window_status.append({**window_context, "complete": window_complete})
        sessions = _merge_session_pages(session_records)
        complete["sessions"] = bool(session_window_status) and all(
            bool(window.get("complete")) for window in session_window_status
        )

        # A bounded window around returned sessions keeps a no-argument cold
        # load from asking every telemetry point in the account.  The bound is
        # only an optimization; an explicit caller range always wins.
        sample_start = start_time
        sample_end = end_time
        if sample_start is None and sample_end is None and sessions:
            starts = [session.get("started_at") for session in sessions if session.get("started_at")]
            ends = [session.get("ended_at") for session in sessions if session.get("ended_at")]
            if starts:
                sample_start = min(starts)
            if ends:
                sample_end = max(ends)

        samples: dict[str, list[dict[str, Any]]] = {}
        if include_samples:
            complete["samples"] = True
            for requested_type in supporting_data_types:
                canonical = _canonical_data_type(requested_type)
                if canonical == "exercise":
                    raise ValueError("supporting_data_types cannot contain exercise")
                stream_samples: list[dict[str, Any]] = []
                stream_raw: list[Any] = []
                token: str | None = None
                stream_complete = False
                for _ in range(max_pages):
                    try:
                        page = self.fetch_supporting_samples(
                            canonical,
                            sample_start,
                            sample_end,
                            page_token=token,
                            page_size=sample_page_size,
                        )
                    except GoogleHealthError as exc:
                        errors.append(self._error_record(canonical, exc))
                        break
                    pages["samples"] += 1
                    stream_samples.extend(page["samples"])
                    stream_raw.append(page["raw"])
                    token = page["next_page_token"]
                    if token is None:
                        stream_complete = True
                        break
                else:
                    errors.append({"stream": canonical, "error": "page_limit_exceeded", "message": f"more than {max_pages} pages"})
                samples[canonical] = stream_samples
                raw_pages["samples"][canonical] = stream_raw
                complete["samples"] = complete["samples"] and stream_complete

        routes: list[dict[str, Any]] = []
        if include_routes:
            complete["routes"] = True
            for session in sessions:
                activity_type = str(session.get("activity_type") or "").strip().upper()
                # ``hasGps`` is optional in real Fitbit-origin records. Probe
                # generic exercises as well because TCX is the authoritative
                # sport/distance source for custom workouts.
                if (
                    session.get("has_gps") is not True
                    and not re.search(r"(?:RUN|JOG|TREADMILL)", activity_type)
                    and activity_type not in {"WORKOUT", "EXERCISE", "UNKNOWN", ""}
                ):
                    continue
                resource_name = session.get("resource_name") or session.get("id")
                if not resource_name:
                    errors.append({"stream": "route", "error": "missing_resource_name"})
                    complete["routes"] = False
                    continue
                try:
                    route = self.export_exercise_tcx(str(resource_name))
                except (GoogleHealthError, ValueError) as exc:
                    if isinstance(exc, GoogleHealthError):
                        errors.append(self._error_record("route", exc, resource_name=resource_name))
                    else:
                        errors.append({"stream": "route", "resource_name": resource_name, "error": str(exc)})
                    complete["routes"] = False
                    continue
                pages["routes"] += 1
                routes.append(route)
                raw_pages["routes"].append(route.get("raw"))

        returned_times: list[datetime] = []
        for session in sessions:
            for key in ("started_at", "ended_at"):
                parsed = _parse_timestamp(session.get(key))
                if parsed is not None:
                    returned_times.append(parsed)
        for stream in samples.values():
            for sample in stream:
                for key in ("timestamp", "start_time", "end_time"):
                    parsed = _parse_timestamp(sample.get(key))
                    if parsed is not None:
                        returned_times.append(parsed)
        oldest = min(returned_times).isoformat().replace("+00:00", "Z") if returned_times else None
        newest = max(returned_times).isoformat().replace("+00:00", "Z") if returned_times else None
        requested_start = _format_filter_time(start_time, civil=False) if start_time is not None else None
        requested_end = _format_filter_time(end_time, civil=False) if end_time is not None else None
        return {
            "sessions": sessions,
            "samples": samples,
            "routes": routes,
            "coverage": {
                "requested_start": requested_start,
                "requested_end": requested_end,
                "oldest_returned": oldest,
                "newest_returned": newest,
                "session_windows": session_window_status,
                "session_window_count": len(session_window_status),
                "pages": pages,
                "record_counts": {
                    "sessions": len(sessions),
                    "samples": {key: len(value) for key, value in samples.items()},
                    "routes": len(routes),
                },
                "sessions_complete": complete["sessions"],
                "samples_complete": complete["samples"],
                "routes_complete": complete["routes"],
                "complete": all(complete.values()) and not errors,
            },
            "errors": errors,
            "raw": raw_pages,
        }

    # ``sync_activity`` is a descriptive alias for route owners that call the
    # aggregate operation from a background sync job.
    sync_activity = fetch_activity

    @staticmethod
    def _error_record(stream: str, error: GoogleHealthError, **extra: Any) -> dict[str, Any]:
        record: dict[str, Any] = {
            "stream": stream,
            "error": error.__class__.__name__,
            "message": str(error),
        }
        if error.status_code is not None:
            record["status_code"] = error.status_code
        if error.retry_after is not None:
            record["retry_after"] = error.retry_after
        if error.details is not None:
            record["details"] = deepcopy(error.details)
        record.update(extra)
        return record


__all__ = [
    "DEFAULT_GOOGLE_HEALTH_SCOPES",
    "GOOGLE_AUTHORIZATION_ENDPOINT",
    "GOOGLE_HEALTH_BASE_URL",
    "GOOGLE_TOKEN_ENDPOINT",
    "GOOGLEHEALTH_ACTIVITY_SCOPE",
    "GOOGLEHEALTH_HEALTH_METRICS_SCOPE",
    "GOOGLEHEALTH_LOCATION_SCOPE",
    "GoogleHealthAuthError",
    "GoogleHealthClient",
    "GoogleHealthError",
    "GoogleHealthRateLimitError",
    "GoogleHealthResponseError",
    "GoogleHealthTimeoutError",
    "GoogleHealthTransportError",
    "build_authorization_url",
    "exchange_code",
    "refresh_token",
]
