-- Runwise production schema for Supabase PostgreSQL.
--
-- This migration is additive and never drops user data. The Render API uses a
-- dedicated server role; browser roles have no table privileges, and OAuth
-- token columns are therefore inaccessible through the Supabase REST API.

-- The owner registry is application-owned. Personal mode authenticates with
-- Google directly, so its fixed owner UUID is not a row in auth.users. A
-- Supabase JWT deployment can provision one row per verified subject.
create table if not exists public.runwise_owners (
    owner_id uuid primary key,
    google_sub varchar(200) unique,
    email varchar(320),
    created_at timestamptz not null default now()
);

create table if not exists public.shoes (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    name varchar(120) not null,
    brand varchar(120) not null default '',
    initial_distance_km double precision not null default 0,
    status varchar(30) not null default 'active',
    purchase_date date,
    image_url varchar(2048),
    rules jsonb not null default '{}'::jsonb,
    constraint shoes_status_check check (status in ('active', 'retired')),
    constraint shoes_image_url_check check (image_url is null or image_url ~* '^https?://[^[:space:]]+$')
);

create table if not exists public.runs (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    title varchar(120) not null,
    started_at timestamptz not null,
    distance_km double precision not null check (distance_km > 0 and distance_km <= 1000),
    duration_seconds integer not null check (duration_seconds > 0 and duration_seconds <= 86400),
    run_type varchar(40) not null default 'run',
    avg_hr integer check (avg_hr is null or (avg_hr >= 20 and avg_hr <= 260)),
    shoe_id bigint references public.shoes(id) on delete set null,
    shoe_assignment varchar(20) not null default 'unassigned',
    shoe_confidence double precision,
    shoe_reason varchar(500),
    notes text not null default '',
    rpe integer check (rpe is null or (rpe >= 1 and rpe <= 10)),
    source varchar(40) not null default 'manual',
    source_id varchar(200),
    content_fingerprint varchar(64),
    dedupe_key varchar(300),
    moving_seconds integer,
    stream_available boolean not null default false,
    constraint runs_shoe_assignment_check check (shoe_assignment in ('manual', 'inferred', 'unassigned')),
    constraint runs_shoe_confidence_check check (shoe_confidence is null or (shoe_confidence >= 0 and shoe_confidence <= 1)),
    unique (owner_id, dedupe_key)
);

create table if not exists public.checkins (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    date date not null,
    sleep_hours double precision check (sleep_hours is null or (sleep_hours >= 0 and sleep_hours <= 24)),
    energy integer not null check (energy between 1 and 5),
    soreness integer not null check (soreness between 1 and 5),
    notes text not null default '',
    unique (owner_id, date)
);

create table if not exists public.run_streams (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    run_id bigint not null references public.runs(id) on delete cascade,
    payload_gzip bytea not null,
    sample_count integer not null check (sample_count between 1 and 50000),
    raw_bytes integer not null check (raw_bytes > 0),
    compressed_bytes integer not null check (compressed_bytes > 0),
    laps jsonb not null default '[]'::jsonb,
    analysis jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (owner_id, run_id)
);

create table if not exists public.shares (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    kind varchar(20) not null check (kind in ('run', 'week', 'month')),
    run_id bigint references public.runs(id) on delete set null,
    share_date date,
    token_hash varchar(64) not null unique,
    snapshot jsonb not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    revoked_at timestamptz
);

create table if not exists public.google_connections (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    provider varchar(40) not null default 'google-health',
    provider_account_id varchar(200),
    refresh_token_encrypted text not null,
    access_token_encrypted text,
    access_token_expires_at timestamptz,
    scopes jsonb not null default '[]'::jsonb,
    connected_at timestamptz not null default now(),
    last_sync_at timestamptz,
    sync_cursor varchar(500),
    sync_status varchar(30) not null default 'connected',
    sync_error varchar(1000),
    metadata_json jsonb not null default '{}'::jsonb,
    unique (owner_id, provider)
);

create table if not exists public.oauth_states (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references public.runwise_owners(owner_id) on delete restrict,
    state_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now(),
    code_verifier_encrypted text
);

create index if not exists runs_owner_started_at_idx on public.runs(owner_id, started_at desc);
create index if not exists runs_owner_source_idx on public.runs(owner_id, source);
create index if not exists shoes_owner_idx on public.shoes(owner_id);
create index if not exists checkins_owner_idx on public.checkins(owner_id);
create index if not exists run_streams_owner_idx on public.run_streams(owner_id);
create index if not exists shares_owner_idx on public.shares(owner_id);
create index if not exists google_connections_owner_idx on public.google_connections(owner_id);
create index if not exists oauth_states_owner_idx on public.oauth_states(owner_id);

-- A NOLOGIN role is used only by the Render API. Keep its passwordless role
-- separate from Supabase's browser roles; an administrator can instead create
-- this role in the dashboard and leave this idempotent block unchanged.
do $$
begin
    create role runwise_api nologin;
exception
    when duplicate_object then null;
end;
$$;

-- Capability routes resolve a hash/token before an owner is known. They are
-- served only by the trusted Render role (browser roles have no privileges),
-- and the API still requires an exact SHA-256 token/state hash plus expiry.
drop policy if exists shares_server_capability on public.shares;
create policy shares_server_capability on public.shares for all to runwise_api
    using (true) with check (true);
drop policy if exists oauth_states_server_capability on public.oauth_states;
create policy oauth_states_server_capability on public.oauth_states for all to runwise_api
    using (true) with check (true);

-- Owner IDs are assigned by the API/JWT boundary and cannot be changed later.
create or replace function public.runwise_owner_immutable()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if tg_op = 'UPDATE' and new.owner_id is distinct from old.owner_id then
        raise exception 'owner_id is immutable';
    end if;
    return new;
end;
$$;

do $$
declare
    table_name text;
begin
    foreach table_name in array array['runwise_owners', 'shoes', 'runs', 'checkins', 'run_streams', 'shares', 'google_connections', 'oauth_states'] loop
        execute format('drop trigger if exists %I_owner_immutable on public.%I', table_name, table_name);
        execute format('create trigger %I_owner_immutable before update on public.%I for each row execute function public.runwise_owner_immutable()', table_name, table_name);
    end loop;
end;
$$;

-- RLS remains enabled even if an operator later grants a server role table
-- access. The API should set request.jwt.claim.sub on a transaction when it
-- uses a role subject to RLS. Supabase's auth.uid() handles direct JWT use.
do $$
declare
    table_name text;
begin
    foreach table_name in array array['runwise_owners', 'shoes', 'runs', 'checkins', 'run_streams', 'shares', 'google_connections', 'oauth_states'] loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('alter table public.%I force row level security', table_name);
        execute format('drop policy if exists %I_owner_isolation on public.%I', table_name, table_name);
        execute format($policy$
            create policy %I_owner_isolation on public.%I
            for all to authenticated, runwise_api
            using (
                owner_id = auth.uid()
                or owner_id::text = nullif(current_setting('request.jwt.claim.sub', true), '')
            )
            with check (
                owner_id = auth.uid()
                or owner_id::text = nullif(current_setting('request.jwt.claim.sub', true), '')
            )
        $policy$, table_name, table_name);
    end loop;
end;
$$;

-- The browser never receives database privileges, especially for encrypted
-- OAuth state and token columns. The Render server role is configured once by
-- an administrator using the least-privilege grants in supabase/README.md.
revoke all on table public.shoes, public.runs, public.checkins, public.run_streams,
    public.shares, public.google_connections, public.oauth_states, public.runwise_owners from anon, authenticated;
revoke all on sequence public.shoes_id_seq, public.runs_id_seq, public.checkins_id_seq,
    public.run_streams_id_seq, public.shares_id_seq, public.google_connections_id_seq,
    public.oauth_states_id_seq from anon, authenticated;

-- A deployment administrator should run these grants as the database owner.
-- They are intentionally separate from browser-facing Supabase keys.
grant usage on schema public to runwise_api;
grant select, insert, update, delete on public.shoes, public.runs, public.checkins,
    public.run_streams, public.shares, public.google_connections, public.oauth_states, public.runwise_owners to runwise_api;
grant usage, select on sequence public.shoes_id_seq, public.runs_id_seq, public.checkins_id_seq,
    public.run_streams_id_seq, public.shares_id_seq, public.google_connections_id_seq,
    public.oauth_states_id_seq to runwise_api;
